wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  fast_connect: true
  domain: !secret wifi_domain

# Enable logging
#logger:

mqtt:
  broker: !secret mqtt_broker
  discovery: True
  port: !secret mqtt_port

ota:
  password: !secret ota_passwd

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
