wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  fast_connect: true
  domain: !secret wifi_domain

# Enable logging
#logger:

mqtt:
  broker: !secret mqtt_broker
  discovery: True
  port: !secret mqtt_port

ota:
  password: !secret ota_passwd

sensor:
  - platform: uptime
    name: ${device_name} Uptime Sensor

text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version
  - platform: wifi_info
    ip_address:
      name: ${device_name} ESP IP Address
    ssid:
      name: ${device_name} ESP Connected SSID
    bssid:
      name: ${device_name} ESP Connected BSSID
