wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  fast_connect: true
  domain: !secret wifi_domain

# Enable logging
logger:
  level: WARN

mqtt:
  broker: !secret mqtt_broker
  discovery: True
  port: !secret mqtt_port

ota:
  password: !secret ota_passwd

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: ${device_name_lower} ESP IP Address
    ssid:
      name: ${device_name_lower} ESP Connected SSID
    bssid:
      name: ${device_name_lower} ESP Connected BSSID
  - platform: wifi_signal
    name: ${device_name_lower} ESP RSSI
    update_internal: 120s
