substitutions:
  device_name: pylon

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

logger: !include ../Common/logger.yaml

mqtt: !include ../Common/mqtt.yaml

ota: !include ../Common/ota.yaml

sensor: !include_dir_list ../Common/sensor

text_sensor: !include_dir_list ../Common/text_sensor

wifi: !include ../Common/wifi.yaml
