esphome:
  name: ${device_name_lower}_switch
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name_upper} Button"
    internal: True
    on_press:
      - switch.toggle: relay

logger: !include ../Base/logger.yaml

mqtt: !include ../Base/mqtt.yaml

ota: !include ../Base/ota.yaml

sensor: !include_dir_list ../Base/sensor

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: gpio
    name: "${device_name_upper} Relay"
    pin: GPIO12
    id: relay

text_sensor: !include_dir_list ../Base/text_sensor

wifi: !include ../Base/wifi.yaml
