esphome:
  name: ${device_name_lower}_climate
  platform: ESP8266
  board: d1_mini

i2c:
  sda: D2
  scl: D3

logger: !include ../Base/logger.yaml

mqtt: !include ../Base/mqtt.yaml

ota: !include ../Base/ota.yaml

sensor:
  - <<: !include ../Base/sensor/wifi_rssi.yaml
  - platform: dht
    model: DHT22
    pin: D5
    temperature:
      name: "${device_name_upper} Temperature"
    humidity:
      name: "${device_name_upper} Humidity"
    update_interval: 120s
  - platform: tsl2561
    name: "${device_name_upper} Ambient Light"
    address: 0x39
    update_interval: 120s

text_sensor: !include_dir_list ../Base/text_sensor

wifi: !include ../Base/wifi.yaml
