<<: !include ../base.yaml

substitutions:
  device_name: bed_room_climate
  room_name: "Bed Room"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

i2c:
  sda: D2
  scl: D3

sensor:
  - platform: adc
    pin: VCC
    name: ${device_name} VCC Voltage
  - platform: dht
    model: DHT11
    pin: D0
    temperature:
      name: "${room_name} Temperature"
    humidity:
      name: "${room_name} Humidity"
    update_interval: 120s
  - platform: tsl2561
    name: "${room_name} Ambient Light"
    address: 0x39
    update_interval: 120s
