<<: !include ../base.yaml

esphome:
  name: ${device_name_lower}_climate
  platform: ESP8266
  board: d1_mini

i2c:
  sda: D2
  scl: D3

sensor:
  - platform: dht
    model: DHT22
    pin: D5
    temperature:
      name: "${device_name_upper} Temperature"
    humidity:
      name: "${device_name_upper} Humidity"
    update_interval: 120s
  - platform: tsl2561
    name: "${device_name_upper} Ambient Light"
    address: 0x39
    update_interval: 120s
