<<: !include ../base.yaml

esphome:
  name: ${device_name_lower}_switch
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name_upper} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${device_name_upper} Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes